### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/gregoire/.config/fastly/viceroy)

### ISSUE THREAD

**Issue by lyrixx** [fastly/cli#526] opened 2022-01-27 10:52 UTC
**Version**

```
Fastly CLI version 1.6.0 (49d5ad0)
Built with go version go1.17.6 linux/amd64
```

**What happened**

```
>…jolicode/redirection.io/clients/fastly(fastly *) fastly compute serve
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local rust toolchain...
✓ Building package using rust toolchain...
✓ Creating package archive...

SUCCESS: Built package 'fastly' (pkg/fastly.tar.gz)

✓ Fetching latest Viceroy release...
✓ Running local server...

/home/gregoire/.config/fastly/viceroy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/gregoire/.config/fastly/viceroy)

ERROR: error during execution process:

/home/gregoire/.config/fastly/viceroy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/gregoire/.config/fastly/viceroy).

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

OS details:

```
>/home/gregoire lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by lyrixx** [comment] 2022-01-27 10:53
Duplicates of #513 I guess

**Comment by lyrixx** [comment] 2022-01-27 10:55
and linked to https://github.com/fastly/Viceroy/issues/120 I guess too

**Comment by lyrixx** [comment] 2022-01-27 11:19
For the record, I "fixed" it by compiling viceroy locally, and by linking the binary:
```
ln -s $(which viceroy) /home/gregoire/.config/fastly/viceroy```

**Comment by Integralist** [comment] 2022-01-27 13:16
Hi @lyrixx 

This actually looks to be a duplicate of https://github.com/fastly/Viceroy/issues/120 (even the workaround 🙂 ).

I'm going to close this issue and I'll leave a message in the Viceroy saying you've also run into this problem.

Thanks

**Closed by Integralist** 2022-01-27 13:16 UTC
Labels: bug
