### ISSUE TITLE
[FEATURE REQUEST] - Allow template initialization from GITHUB private repos

### ISSUE THREAD

**Issue by byteshiva** [fastly/cli#510] opened 2022-01-13 12:46 UTC
**Is your feature request related to a problem? Please describe.**
I'm unable to initialize or fetch from a private repo. Can we have ways to make it work!

**Additional context**

`fastly compute init` fails to fetch contents from GitHub private repository, 
```
root@3d365fc0a1be:/home/clientinfo# fastly compute init --from=https://github.com/byteshiva/clientInfo

Creating a new Compute@Edge project (using --from to locate package template).

Press ^C at any time to quit.

Name: [clientinfo] 
Description: 
Author: [chnshivaind@gmail.com] 

✓ Initializing...
- Fetching package template...
✗ Fetching package template...

ERROR: failed to get package: 404 Not Found.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md

ERROR: there was a problem updating the versioning information for the Fastly CLI:

Get "https://developer.fastly.com/api/internal/cli-config": context deadline exceeded.
```

ps:-
To make it work I had to change the GITHUB Repository permission to public.

**Comment by Integralist** [comment] 2022-01-13 13:03
Hi @byteshiva 👋🏻 

I would recommend SSH over HTTP:

```bash
fastly compute init --from=git@github.com:byteshiva/clientInfo.git
```

Thanks.

**Comment by byteshiva** [comment] 2022-01-13 15:09
I created a new Private Repository clone of  `git@github.com:byteshiva/clientInfo.git`

Added the Public key of the remote machine in GITHUB to allow full write access.

Still getting the same error: 

![image](https://user-images.githubusercontent.com/10637299/149355082-043f48fa-c887-45c5-9337-9516d7e66f6b.png)

**Comment by byteshiva** [comment] 2022-01-13 15:26
The above got fixed by adding the following statement.
```
$ echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
```
In the case of automation, do I need to still add the public key of the remote machine to GITHUB?

![image](https://user-images.githubusercontent.com/10637299/149358383-153079f5-7c4d-4e20-9a96-e1938bb356b5.png)

**Comment by Integralist** [comment] 2022-01-13 15:27
Thanks @byteshiva for providing these details.

So I've did the same and it works...

1. Clone your public repo locally.
2. Delete the `.git` directory.
3. Create a new private repo.
4. Initialise a new git repo within the local directory and set the remote to the private repo.
5. Push up all the code to the private repo.
6. Open a new terminal directory and use the Fastly CLI to clone from the private repo.

<img width="746" alt="Screenshot 2022-01-13 at 15 21 25" src="https://user-images.githubusercontent.com/180050/149358323-ef0b83e1-5ba0-462b-9c84-75b7b5f59121.png">

So this looks to be a possible issue with your SSH configuration maybe?

Maybe validate you can access GitHub using...

```
ssh -T git@github.com
ssh-agent -s
ssh-add -K ~/.ssh/<your_github_private_key>
```

**Comment by Integralist** [comment] 2022-01-13 15:29
Oh great, I see you got the cloning error fixed. 👍🏻 

re: the other error `context deadline exceeded` that looks to be a duplicate of https://github.com/fastly/cli/issues/289 so I'm going to close this issue and would recommend you comment on the other issue instead. It appears to be an IPv6 issue and a few users have noted that once they disable IPv6 on their machine they no longer get the error.

Thanks!

**Closed by Integralist** 2022-01-13 15:29 UTC
Labels: feature request
